version: '2'
services:
  client:
    image: client
    build: ./client/
    links:
      - broker
    environment:
      - BROKER_URL=http://broker:3000
    depends_on:
      - kafka
  worker:
    image: worker
    build: ./worker/
    links:
      - broker
    depends_on:
      - kafka
  broker:
    image: broker
    build: ./broker/
    
    expose:
      - "3000"
    depends_on:
      - kafka
   # networks:
    #  - net_backend
   # environment:
    #  - WAIT_HOSTS=kafka:9092
     # - WAIT_BEFORE_HOSTS=10


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
    - "2182:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    labels:
      - 'custom.project=kafkajs-zstd'
      - 'custom.service=kafka'
    depends_on:
      - zookeeper
    ports:
      - 9094:9092
    

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29094,PLAINTEXT_HOST://localhost:9094
      
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29094,PLAINTEXT_HOST://0.0.0.0:9092
      
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_LOG4J_LOGGERS: 'kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO'
      CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      
