version: '2'
services:
  client:
    image: client
    build: ./client/
    links:
      - broker
    environment:
      - BROKER_URL=tcp://broker:3000
  worker:
    image: worker
    build: ./worker/
    links:
      - broker
  broker:
    image: broker
    build: ./broker/
    links:
      - kafka 
    expose:
      - "3000"
  kafka:
    image: kafkajs
    ports: 
    - 9092:9092
    environment:
      KAFKA_X: 1
    build: ./configuration/