version: '2'
services:
  client:
    image: client
    build: ./client/
    links:
      - broker
    environment:
      - BROKER_URL=tcp://bro:9998
  worker:
    image: worker
    build: ./worker/
    links:
      - broker
    environment:
      - BROKER_URL=tcp://bro:9999
  broker:
    image: broker
    build: ./broker/
    links:
      - kafka 
    expose:
      - "9998"
      - "9999"
  kafka:
    image: kafkajs
    build: ./configuration/